<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="../../public/css/login.css">
</head>
<body>
<div class="bg">
    <div class="login-box">
        <img src="../../public/imges/avator.png" class="avator">
        <h1>Login here</h1>
        <form action="../login/login" method="post" autocomplete="off">
            <p>Username</p>
            <input type="text" name="username" placeholder="Enter Username" autocomplete="nope">
            <p>Password</p>
            <input type="password" name="password" placeholder="Enter Password" autocomplete="new-password">
            <input type="submit" name="submit" value = "Login">
            <a href="#">Forgot Password</a>
        </form>
        <footer class="footer">
            Created by Irfan Khan &copy 2019
        </footer>
    </div>
</div>

</body>
</html>
